### ISSUE TITLE
404 при сборке

### ISSUE THREAD

**Issue by dahiko2** [DJWOMS/pysonet#5]
Привет!

При сборке происходит обращение на несуществующий рерсурс https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py и соответственно все ломается.
![image_2024-11-05_16-12-26](https://github.com/user-attachments/assets/abab098b-ac51-4bad-a033-5662079b9a59)

**Comment by DJWOMS** [comment]
Привет. Исправил.
[fix: dockerfile](https://github.com/DJWOMS/pysonet/commit/c03de18a93e2f59580a7c57530b962cd40849e4d)
